### PR TITLE
 a simple isStem function

### PR DESCRIPTION
**Pull request by Real-John-Cheung**
refer to https://github.com/dhowe/rita/issues/131
not sure if this is the most efficient way... but it can handle the stem of lexicon word

### CODE REVIEW

**Comment by dhowe** [comment]
- [ ] please add comments detailing how the algorithm works
- [ ] how are you checking whether the results are actually correct stems?

**Comment by Real-John-Cheung** [comment]
> how the algorithm works 

basically it tries to find words in the dictionary that has the same start letters with the input and check if stem() those words return the input
take 'bodi' as an example, first the algorithm searches with `/^bodi/`in the dictionary, sort them according to the length (short words first) and check each word if stem() it return bodi.  As no word is found, it will then do the same with `/^bod/` in this case, body is the word it will find, so `true` is returned, otherwise it will keep going with `/^bo/` until the string length < 2 (not searching with a single letter since that doesn't make much sense) and return `false`

> how are you checking whether the results are actually correct stems? 

hmm this is a bit tricky, as described above, this `isStem()` function is totally relied on `RiTa.stem()`, so the accuracy also depends on the accuracy of `RiTa.stem()`

**Comment by dhowe** [comment]
Interesting approach. We need to check the performance of the algorithm against a relatively large set of words, both in the lexicon and not.

You can use this site: https://snowballstem.org/demo.html for testing interactively or sample from this very large wordlist: https://github.com/snowballstem/snowball-data/tree/master/english

We should do ~50 words in our lexicon and ~50 not.

**Comment by Real-John-Cheung** [comment]
add 50 should pass cases and 55 should not pass cases.

it is slower in the should not pass cases since the algorithm tries more
on my machine it takes around 1200ms to run-through all ~110 tests

**Comment by dhowe** [comment]
* I upped the timeout limit, but we may need to reduce the number of tests
* I also did some refactors to speed up the function and the tests
* question: where will this function be used?

**Comment by Real-John-Cheung** [comment]
>where will this function be used? 

I guest when the user encounter a stem and want to do something with it (like conjugation or rhyme or pos etc)...
So maybe it will be useful for this function to return the word it found instead of a boolean true?

**Comment by dhowe** [comment]
not sure of what the use case is for this function, but in any case it makes sense to have it return either the word or undefined, rather than true/false.

**Pull request merged**
