### PR TITLE
Fix #223

### PR DESCRIPTION
**Pull request by CyrusSUEN**

### CODE REVIEW

**Comment by dhowe** [comment]
I dont understand this PR. Java was working fine, and had none of this extra code, no?

**Comment by CyrusSUEN** [comment]
Yes. After using the code snippet you sent me, 1 of the 2 known issues in untokenize() has been solved. (RiTa.testTokenizeAndBack)

I then added extra code and condition to solve the remaining known issue: RiTa.testUntokenize.

Now that both known issues have been fixed in the PR.

**Comment by CyrusSUEN** [comment]
I'm not familiar with the regex syntax in Java so the fix for known issue RiTa.testUntokenize in RiTa Java has not been ported right away.

**Comment by dhowe** [comment]
Correct me if I am wrong, but Java was working correctly. So all that needed to be done was to make JS work in the same way. Now I see a bunch of new code in JS that needs to be back-ported to Java (which was not broken)...

**Comment by CyrusSUEN** [comment]
It's now broken for this particular test case: https://github.com/dhowe/RiTa/blob/master/java/rita/test/KnownIssuesTest.java#L22-L34
capture

**Comment by dhowe** [comment]
Ok, I will take a closet look at this when I have time

**Pull request merged**
